name: ✨ Feature Request
description: Suggest a new feature or improvement.
title: "✨ Feature: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to suggest a new feature! Before you start, please check if someone else has already suggested something similar.
    - type: textarea
      id: feature-description
      attributes:
          label: 💡 What feature would you like to see?
          description: Describe the feature and how it would improve the project.
      validations:
          required: true
    - type: textarea
      id: implementation-examples
      attributes:
          label:
              🔍 Have you seen a similar feature in another tool, plugin, etc?
              List them here.
    - type: textarea
      id: potential-implementation
      attributes:
          label: 🛠️  Do you have any ideas on how to implement this?
          description: If you have thoughts on how this could be added, share
              them here.
