name: Code quality checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ["**/*.rs"]

jobs:
  quality-check:
    name: Check formatting and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache rustup installation
        id: cache-rustup
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: rustup-cache-key
          restore-keys: |
            rustup-cache-key

      - name: Install rustup
        if: steps.cache-rustup.outputs.cache-hit != 'true'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"

      - name: Run clippy
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo clippy -- -D warnings

      - name: Run rustfmt
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo fmt --check
