name: Commitlint

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install commitlint
        run: |
          npm install --no-save commitlint@latest conventional-changelog-conventionalcommits

      - name: Lint commits
        run: |
          npm install --no-save @commitlint/cli @commitlint/config-conventional
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

          FROM_SHA=""
          TO_SHA="${{ github.sha }}"

          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            FROM_SHA="${{ github.event.pull_request.base.sha }}"
            TO_SHA="${{ github.event.pull_request.head.sha }}"
          else
            FROM_SHA="${{ github.event.before }}"
            TO_SHA="${GITHUB_SHA}"
          fi

          echo "Linting commits from $FROM_SHA to $TO_SHA"
          npx commitlint --from "$FROM_SHA" --to "$TO_SHA" --verbose
