name: Automated release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  compile-binaries:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      BIN_NAME: script
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile binary
        run: |
          cargo build --release

      - name: Rename binary
        shell: bash
        run: |
          EXT=""
          if [[ ${{ matrix.os }} == "Windows" ]]; then
            EXT=".exe"
          fi

          mkdir -p dist
          cp target/release/${{ env.BIN_NAME }}$EXT dist/${{ env.BIN_NAME }}-${{ runner.os }}$EXT

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binary
          path: dist/

  release:
    name: Create release
    needs: compile-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Run Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_SECRET }}
          release-type: rust

      - name: Upload Release Artifact
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find dist -type f
          gh release upload ${{ steps.release-please.outputs.tag_name }} dist/*/* --clobber
