name: Automated release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    name: Release-please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Run Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_SECRET }}
          release-type: rust

      - name: Debug outputs
        run: |
          echo "release_created: ${{ steps.release-please.outputs.release_created }}"
          echo "tag_name: ${{ steps.release-please.outputs.tag_name }}"

      - name: Set job outputs
        id: set-outputs
        run: |
          echo "release_created=${{ steps.release-please.outputs.release_created }}" >> "$GITHUB_OUTPUT"
          echo "tag_name=${{ steps.release-please.outputs.tag_name }}" >> "$GITHUB_OUTPUT"

  compile-code:
    needs: generate
    if: ${{ needs.generate.outputs.release_created }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    env:
      BIN_NAME: script
      APP_NAME: scriptian
    steps:
      - uses: actions/checkout@v4

      - name: Install zip (Windows only)
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install zip -y

      - name: Install Rust
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add target for cross-compilation
        run: |
          rustup target add ${{ matrix.target }}

      - name: Compile binary
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            cargo build --release
          else
            cargo install cross
            cross build --release --target ${{ matrix.target }}
          fi

      - name: Package the binary
        run: |
          EXT=$([[ ${{ matrix.os }} == "windows-latest" ]] && printf ".exe" || printf "")
          ARCH=""

          case "${{ matrix.target }}" in
            x86_64-unknown-linux-gnu)    ARCH="linux-x64" ;;
            aarch64-unknown-linux-gnu)   ARCH="linux-arm64" ;;
            x86_64-pc-windows-gnu)      ARCH="windows-x64" ;;
            x86_64-apple-darwin)         ARCH="macos-x64" ;;
            aarch64-apple-darwin)        ARCH="macos-arm64" ;;
            *) echo "Unknown target"; exit 1 ;;
          esac

          mkdir -p dist
          zip -j dist/${{ env.APP_NAME }}-$ARCH.zip \
                 README.md \
                 LICENSE \
                 target/release/${{ env.BIN_NAME }}$EXT

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.target }}-package
          path: dist/

  update-release:
    name: Update release
    needs: [compile-code, generate]
    runs-on: ubuntu-latest
    if: ${{ needs.generate.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Add release binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find dist -type f

          find dist -name "*.zip" -exec gh release upload ${{ needs.generate.outputs.tag_name }} {} --clobber \;

      - name: Generate checksums
        id: sha256
        run: |
          cd dist
          CHECKSUMS=$(find . -name "*.zip" -exec sha256sum {} \;)
          echo "checksums<<EOF" >> $GITHUB_OUTPUT
          echo "$CHECKSUMS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Append checksums to release notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ needs.generate.outputs.tag_name }}
          CHECKSUMS: ${{ steps.sha256.outputs.checksums }}
        run: |
          CURRENT_BODY=$(gh release view "$TAG_NAME" --repo "$GITHUB_REPOSITORY" --json body -q '.body')

          NEW_BODY=$(cat <<EOF
          ${CURRENT_BODY}

          ## SHA256 Checksums
          \`\`\`
          ${CHECKSUMS}
          \`\`\`
          EOF
          )

          gh release edit "$TAG_NAME" --repo "$GITHUB_REPOSITORY" --notes "$NEW_BODY"

      - name: Add shasum.txt
        env:
          TAG_NAME: ${{ needs.generate.outputs.tag_name }}
          CHECKSUMS: ${{ steps.sha256.outputs.checksums }}
        run: |
          echo "$CHECKSUMS" >> shasum.txt
          gh release upload "$TAG_NAME" shasum.txt --clobber \;
